### PR TITLE
chore: rolling back Firecracker v1.0.0 changes

### LINKED ISSUE #392: Rollback Firecracker 1.0.0 changes
**What happened:**
When running flintlock with Firecracker 1.0.0 we see the issue with cloud-init and getting data from the MMDS:

```
[   13.526932] cloud-init[940]: [2022-02-11 12:57:36] 2022-02-11 12:57:36,217 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloudNet'> failed
...
[   14.734609] cloud-init[1147]: [2022-02-11 12:57:37] 2022-02-11 12:57:38,001 - cc_final_message.py[WARNING]: Used fallback datasource
```

We will temporarily rollback the firecracker 1.0.0 changes on main and then look separately at adding this back in

**What did you expect to happen:**

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- flintlock version:
- containerd version:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:

Rolling back Firecracker 1.0.0 changes temporarily due to issues. These will be fixed again in #390 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #392 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Callisto13** [comment]
Is this just rolling back? Is there something coming later to fix the issue or are we also rolling back to an earlier firecracker?

**Comment by yitsushi** [comment]
Wouldn't it be easier to just press the revert button on the original PR?

**Review by yitsushi — CHANGES_REQUESTED** [review]
This is missing from the revert:
`infrastructure/firecracker/testdata/vm_config.json`

**Comment by richardcase** [comment]
> Is this just rolling back? Is there something coming later to fix the issue or are we also rolling back to an earlier firecracker?

There is a change to re-add and get to the bottom of why the MMDS is getting hit but that will come later in #390 . Need to get back to a know working state short term for the EKS-A changes.

**Comment by Callisto13** [comment]
hmmm i'll allow it

**Pull request merged**
