### PR TITLE
Add service file for systemd

### PR DESCRIPTION
**Pull request by Callisto13**
As part of my docs writing I realised that having an option to manage flintlockd with systemd looks a bit more pro than "start the server with an `&`".

The `--parent-iface` flag is of course required and means some sort of user input. I did consider an EnvironmentFile, but it's a bit "eh" and the systemd creators deeply regret its inclusion.
I am documenting that users need to do something here.

### CODE REVIEW

**Comment by yitsushi** [comment]
We have viper included, i wonder why we don't have a `--config` option.

**Comment by Callisto13** [comment]
are we not removing viper?

**Comment by Callisto13** [comment]
but yeh if urfave/cli has a config file then we can use that

**Comment by richardcase** [comment]
> but yeh if urfave/cli has a config file then we can use that

The PR that Soule has done for urfave/cli does  have a config file option.

**Comment by Callisto13** [comment]
👍  do we want that as part of this PR or can i move forward with this one and come back to that?

**Comment by richardcase** [comment]
> +1 do we want that as part of this PR or can i move forward with this one and come back to that?

Lets come back to it

**Pull request merged**
